//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fuatobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciNot
    {
        public int OgrenciNotID { get; set; }
        public int OgrenciId { get; set; }
        public int DersId { get; set; }
        public byte VizeNotu { get; set; }
        public byte FinalNotu { get; set; }
        public Nullable<byte> ButunlemeNotu { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
    }
}
