//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fuatobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmen
    {
        public int OgretmenId { get; set; }
        public string kullanıcıAdı { get; set; }
        public string Password { get; set; }
    }
}
