//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fuatobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOgrenciDers
    {
        public string DersAd { get; set; }
        public int OgrenciDersID { get; set; }
        public int OgrenciId { get; set; }
        public string SinifAd { get; set; }
        public string OgrenciNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> SinifId { get; set; }
        public int DersId { get; set; }
    }
}
